---
# https://github.com/hassio-addons/addon-base
build_from:
  aarch64: ghcr.io/hassio-addons/base:stable
  amd64: ghcr.io/hassio-addons/base:stable
upstream_repo: "grafana/alloy"
upstream_version_arg: ALLOY_VERSION
upstream_version_arg_prefix: v
args:
  ALLOY_VERSION: "v1.20.1"
