---
# https://github.com/hassio-addons/addon-base
# This file exists only so GitHub's generic discover workflow (which requires
# both config.yaml and build.yaml) finds this app.
build_from:
  aarch64: ghcr.io/hassio-addons/base:stable
  amd64: ghcr.io/hassio-addons/base:stable
