---
# https://github.com/hassio-addons/addon-base
build_from:
  aarch64: ghcr.io/hassio-addons/base:stable
  amd64: ghcr.io/hassio-addons/base:stable
upstream_repo: "pgadmin-org/pgadmin4"
args:
  PGADMIN_VERSION: "9.18"
upstream_version_arg: PGADMIN_VERSION
