---
# https://github.com/hassio-addons/addon-base
build_from:
  aarch64: ghcr.io/hassio-addons/base:stable
  amd64: ghcr.io/hassio-addons/base:stable
upstream_repo: "cloudflare/cloudflared"
upstream_version_arg: CLOUDFLARED_VERSION
args:
  CLOUDFLARED_VERSION: "2026.9.3"
