---
# https://github.com/hassio-addons/addon-base
build_from:
  aarch64: ghcr.io/hassio-addons/base:stable
  amd64: ghcr.io/hassio-addons/base:stable
upstream_repo: "postgres/postgres"
upstream_tag_prefix: "REL_18_"
upstream_tag_pattern: '^REL_18_[0-9]+$'
upstream_version_arg: POSTGRES_VERSION
args:
  POSTGRES_VERSION: "18.6"
